site_name: Spotify Electron Documentation
site_author: Antonio Martinez Fernandez
repo_url: https://github.com/AntonioMrtz/SpotifyElectron
site_description: Documentation for Spotify Electron, an open-source cross-platform music streaming app
remote_branch: gh-pages

nav:
  - Home: index.md
  - Backend:
    - Set up: backend/SETUP.md
    - Enviroment: backend/Enviroment.md
    - File Structure: backend/File-Structure.md
    - Architecture: backend/Architecture.md
    - Docker: backend/Docker.md
  - Frontend:
    - Set up: frontend/SETUP.md
  - How to contribute: CONTRIBUTING.md
  - Git convention: Git-Convention.md
  - Contributors: CONTRIBUTORS.md
  - Vision: VISION.md
  - Code of conduct: CODE_OF_CONDUCT.md


theme:
  logo: assets/logo.png
  name: material
  features:
    - navigation.indexes
  palette:
    - scheme: slate
      primary: black
      accent: blue
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
    - scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

plugins:
  - mkdocstrings
  - search

markdown_extensions:
  - mdx_truly_sane_lists
