target-version = "py311"

# Same as Black.
line-length = 88
indent-width = 4

[lint]
extend-select = [
    "UP",  # pyupgrade
    "TRY",
    "I",
    "SIM",
    "R"
]

# Allow fix for all enabled rules (when `--fix`) is provided.
fixable = ["ALL"]
unfixable = []

[format]
quote-style = "double"
indent-style = "space"
skip-magic-trailing-comma = false
line-ending = "auto"

