name: Backend Tests

on:
  pull_request:
    branches:
      - 'master'
      - 'master-*'
jobs:

  run_tests:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python 3.10
        uses: actions/setup-python@v3
        with:
          python-version: "3.10"
          architecture: "x64"
        env:
          AGENT_TOOLSDIRECTORY: /opt/hostedtoolcache

      - name: Install dependencies
        working-directory: Backend
        run: pip install -r requirements.txt && pip install -r requirements_test.txt

      - name: Run tests
        working-directory: Backend/src
        run: python -m pytest -s
        env:
          MONGO_URI : ${{ secrets.MONGO_URI }}
          SECRET_KEY_SIGN : ${{ secrets.SECRET_KEY_SIGN }}
          DISTRIBUTION_ID : ${{ secrets.DISTRIBUTION_ID }}


      - name: Fail workflow on test failure
        if: ${{ failure() }}
        run: exit 1

