name: Generate OpenAPI Schema

on:
  pull_request:
    types:
      - closed

jobs:
  generar-y-guardar-documentacion:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest

    steps:
      - name: Checkout del repositorio
        uses: actions/checkout@v2
        with:
          persist-credentials: false
          token: ${{ secrets.PAT }}

      - name: Configurar Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.11

      - name: Install dependencies
        working-directory: Backend/
        run: |
          python -m venv venv
          source venv/bin/activate
          pip install -r requirements.txt
          python -m app.tools.generate_openapi
        env:
            MONGO_URI : none
            SECRET_KEY_SIGN : none
            SERVERLESS_FUNCTION_URL : none
            ARCH : BLOB
            ENV_VALUE : PROD

      - name: Add and commit changes
        working-directory: Electron/src/swagger/
        run: |
          git config --local user.email "actions@github.com"
          git config --local user.name "GitHub Actions"
          git add openapi.json
          git commit -m "docs: Update OpenAPI Schema"

      - name: Pushing to the protected branch 'protected'
        uses: CasperWA/push-protected@v2
        with:
          token: ${{ secrets.PAT }}
          branch: ${{ github.base_ref }}
